"""Shared ChronoSeek constants and runtime defaults."""

from pathlib import Path

PROTOCOL_VERSION = "2026-04-10"

DEFAULT_NETUID = 1
DEFAULT_MECHID = 0
DEFAULT_NETWORK = "finney"
DEFAULT_WALLET_NAME = "default"
DEFAULT_HOTKEY_NAME = "default"
DEFAULT_WALLET_PATH = "~/.bittensor/wallets/"
DEFAULT_LOG_LEVEL = "INFO"

DEFAULT_MIN_VALIDATOR_STAKE = 10000.0
DEFAULT_AXON_PORT = 8091
DEFAULT_AXON_HOST = "0.0.0.0"
DEFAULT_CHUTES_API_BASE_URL = "https://api.chutes.ai"
DEFAULT_CHRONOSEEK_LOGO_URL = "https://chronoseek.org/logo.png"
DEFAULT_CHUTE_BASE_NAME = "chronoseek-runtime"
DEFAULT_CHUTES_HF_HOME = "/data/huggingface"
DEFAULT_CHUTES_YTDLP_DENO_PATH = "/opt/deno/bin/deno"

DEFAULT_TASK_DATASET_PATH = ""
DEFAULT_TASK_SPLIT = "validation"
DEFAULT_REQUIRE_ACCESSIBLE_VIDEOS = True
DEFAULT_TASK_MAX_SAMPLING_ATTEMPTS = 50
DEFAULT_ENABLE_HARDENED_TASKS = True
DEFAULT_VALIDATOR_TASK_SECRET = ""
DEFAULT_HARDENED_TASK_MAX_GENERATION_ATTEMPTS = 5
DEFAULT_TASK_QUERY_VARIANTS_PATH = ""
DEFAULT_TASK_CLIP_CACHE_DIR = str(
    Path.home() / ".cache" / "chronoseek" / "task-clips"
)
DEFAULT_TASK_ARTIFACT_MANIFEST_PATH = ""
DEFAULT_TASK_ARTIFACT_PREFIX = "task-clips"
DEFAULT_TASK_CLIP_TTL_HOURS = 6.0
DEFAULT_TASK_CLIP_CLEANUP_INTERVAL_SECONDS = 900.0
DEFAULT_TASK_DELETE_REMOTE_ARTIFACTS = False
DEFAULT_TASK_VIDEO_COOLDOWN_HOURS = 24.0
DEFAULT_TASK_CAPTION_COOLDOWN_HOURS = 168.0
DEFAULT_TASK_MIN_CLIP_DURATION_SECONDS = 30.0
DEFAULT_TASK_MAX_CLIP_DURATION_SECONDS = 180.0
DEFAULT_TASK_SOURCE_DOWNLOAD_TIMEOUT_SECONDS = 120
DEFAULT_TASK_ENCODING_PROFILE_NAME = "h264-720p-v1"
DEFAULT_TASK_CLIP_MAX_WIDTH = 1280
DEFAULT_TASK_CLIP_MAX_HEIGHT = 720
DEFAULT_TASK_CLIP_VIDEO_BITRATE = "1500k"
DEFAULT_TASK_CLIP_AUDIO_BITRATE = "96k"
DEFAULT_ENABLE_ADVERSARIAL_TASK_TRANSFORMS = True
DEFAULT_ENABLE_TASK_ENCODING_PROFILE_VARIANTS = True
DEFAULT_CANARY_TASK_RATE = 0.0
DEFAULT_ABSENT_CANARY_QUERIES = ""
DEFAULT_MAX_ACTIVE_TASKS_PER_SOURCE_VIDEO = 0
DEFAULT_MAX_ACTIVE_TASKS_PER_SOURCE_CAPTION = 0
DEFAULT_MAX_ACTIVE_TASKS_PER_QUERY_VARIANT = 0
DEFAULT_MAX_ACTIVE_TASKS_PER_TRANSFORM = 0

DEFAULT_VALIDATOR_EVAL_TOP_K = 1
DEFAULT_SCORE_EMA_ALPHA = 0.1
DEFAULT_SCORE_RELIABILITY_WEIGHT = 0.0
DEFAULT_SCORE_CONSISTENCY_WEIGHT = 0.0
DEFAULT_SCORE_SUSPICION_WEIGHT = 0.0
DEFAULT_TASK_MAX_PREDICTION_DURATION_SECONDS = 60.0
DEFAULT_ENABLE_LATENCY_MULTIPLIER = False
DEFAULT_LATENCY_GRACE_SECONDS = 30.0
DEFAULT_LATENCY_MIN_MULTIPLIER = 0.85

DEFAULT_HIPPIUS_S3_ENDPOINT_URL = "https://s3.hippius.com"
DEFAULT_HIPPIUS_S3_PUBLIC_BASE_URL = "https://s3.hippius.com"
DEFAULT_HIPPIUS_S3_BUCKET = "chronoseek"
DEFAULT_HIPPIUS_S3_REGION = "decentralized"
DEFAULT_HIPPIUS_S3_TIMEOUT_SECONDS = 60.0

DEFAULT_VIDAIO_COMPRESSION_ENABLED = True
DEFAULT_VIDAIO_API_BASE_URL = "https://api.vidaio.io"
DEFAULT_VIDAIO_TIMEOUT_SECONDS = 60.0
DEFAULT_VIDAIO_POLL_INTERVAL_SECONDS = 15.0

DEFAULT_VIDEO_AVAILABILITY_CACHE_PATH = ""
DEFAULT_ACCESSIBLE_VIDEO_CACHE_PATH = ""
DEFAULT_INACCESSIBLE_VIDEO_CACHE_PATH = ""
DEFAULT_VIDEO_AVAILABILITY_CACHE_TTL_HOURS = 24.0
DEFAULT_VIDEO_AVAILABILITY_TIMEOUT = 20

DEFAULT_MINER_REQUEST_TIMEOUT_SECONDS = 150.0
DEFAULT_MINER_SUBMISSION_CACHE_TTL_SECONDS = 300.0
DEFAULT_MINER_SUBMISSION_REFRESH_INTERVAL_SECONDS = 60.0
DEFAULT_MINER_SUBMISSION_HEALTH_TIMEOUT_SECONDS = 10.0
DEFAULT_ENFORCE_ONE_HOTKEY_ONE_SUBMISSION = True
DEFAULT_VALIDATOR_TELEMETRY_PATH = ""
DEFAULT_CHUTES_BASE_DOMAIN = "chutes.ai"
DEFAULT_MINER_EMISSION_BURN_PERCENT = 0.0

DEFAULT_HF_CACHE_DIR = ""
DEFAULT_HF_ACTIVITYNET_FILENAME = ""
DEFAULT_VALIDATOR_HEARTBEAT_TIMEOUT_SECONDS = 600
